// ==========================================================================
// <copyright file="TestCase1Data.cs" company="Genetec">
//   Copyright (c) 2018 by Genetec
//   All rights reserved. May be used only in accordance with a valid Source Code License Agreement.
// </copyright>
// Created: 01/03/2021
// Last update: 01/03/2021
// ==========================================================================

namespace UnitTests.TestCases
{
    public static class TestCase2
    {
        public static TestCaseModel Model => new TestCaseModel { 
            TestCasesCount = 100,
            Data =
            @"
            baccbbacababacacbaccaacccbccaccbabac
            acaacababbcbabbbbbaaaabacaabbcbac
            bcbcacacbbaaccbaacbccaca
            ccbaccbcabcabcbacbaaabbacaaabaabbabacaabbcbabacbcccbaabacccaacbbaacabcbacabb
            aaba
            cbbbcabbbababcababbccbcacbbaacbaacbcabbbbbbabcbbbbaacaabbcacbbccabcaaccbaabbab
            bcbccbcbbababcaaacbbcaab
            bacbccacacbbabaacbbacaacbcbbcaccabaaaccabcccaacccccbcbbaaacaabcbcbb
            acaccaccabcaaacababcaacaccacbccbbababaacaabbaaccbbbccabcababacaabcbaacaacbcacccbbaabacbcabacbcccbaa
            cbaccaccacabccabbbaaabcbbccccccaacababaaacbbcbcbaabac
            abacbbcabbabcacaabcacbbbbaccaccbacaaaabcbcbbabbccbcb
            bacbacabbbcbccaabccbaabacaabcaabb
            cababacaacaacbcccbabccccbccbacabca
            abbababccaccabccacbaabbbcacbccaaccbacabaaacbccbabaacbbbbcacbbbcaabbabcacabbcbccacbcbcbcab
            cabcacaacccbbacbaaabbbcaaccacaacccbabcacbaaababbbaacbcabccbcaabccab
            cbbbcccbabbbbbbabbcbbbabcccccacacbbcabbaacccbaaaccbabbcbbcbccbcbaabbcaccaccbaacababcabccabbacabcbb
            acbacaacbbbacabcbcbaaccaacbcbabccaaacbcacbabccbacabcabcaacbaaa
            ababababbcaaccbaccbcaaabbcaccbbaccbcacacaaccbbcbbcabcabbababaabccbcbbbabcaaacbb
            baabbbacababbcbcbbaacabb
            aaacccaacbcbcccbaaaaacccacbcbaabbbacabcaabbabacbcacaabccbbbccbcbaaa
            cabacaabcaacbcccbcbaaccaccbcacccaacacabcacbccbcbbabbbcbabb
            cbcbcbbaacaaaccaaaabcaaacccabbbbaaaac
            bacbaabcbbabacaa
            cabacccaaac
            abaabbcbcbacabcccabcbcaacccaccccacb
            babbccaccaabbbacbabaabbaabcbbabcbccbccacbbacccababababbabbccaaabcca
            cbbaccbacbccacaaccaabcabcaaccbccabaa
            bbaabaabbaabbbcbcbbacbaababcbcbbbcbcccbbcccbccabacbaaccbaab
            aabcaacacbbabbcaaccbbbabccaacaabbcbbaaaccbabbccccccbbc
            abccbcaa
            abaacaacacbcbbbbbbacbcbabaccb
            bbcbccabbbaaacbcbcbcccbaaabacaaacacccababbbcacbccaccababcccbacacbabaacc
            bababaaabaacccabbcbccbbabbbcbbbababaabcbbcabbaaaaccbacccabbbcacbaabbcacbbb
            acccabcccbbccacbccbbbcbcbbcaaabcbabbbabbaccccbbcbaa
            abbcbcccabbbccacbbabbabbbaaabcccbcbacaacabccccbbcacbabcccaabaaabcbabaacacb
            caca
            aabaabaccbbccbbbbbbccacabaacabaaccbcacacbbcaabccaabbbbccccacbbabacbbc
            baabbcabbbcacbccabcbcacacacbcbaaabbbbbccacaabbabcabcaacbbbaabbbcaaababcabcbcbcbbccabb
            cccaabbcacccacacacaabbcaacacbcabbabcaabbcbabbbbcacccccaacbcaaabccacacabbccabbabccbccbcabbacc
            ccbcbbbcabaccbbcabacacabcbaabacaabacaabacc
            baabbcbacabbbcccbaccaaacbbbbababcaabaccabaccbccacbaccbcacccabbcbcaaacabbbabcaabcbb
            aaabcaccbabbacbaabbbbcabaaccaaabbcbacbaccaaca
            aabbaabbbbcbcacacbcbcccbbbbcacbabcabcbacbcabbababbbcaaacbcccbaacbbbbacababcbcbcbaaabbaaaaa
            caaccbcbcccacbbabaccaaabcbccccccaacacccbcbcbababbabbcccbbcbbbbacbbabacacab
            bcaacabbcbbcababacaab
            aaccbaacacaaacbcacbcbcbcbcbbcaaaaacabacbacbbcabaccabc
            abacaaababcababbcc
            abbbccba
            cccabaacbabccaa
            bcaaccbabcca
            aabbcccaaccbabbbbcababaaaababccccaacababacacacbaba
            cbaacbbaabcabbabccbbbacabbccbccaccbcbacccccaaacbaaccbccaacacaaaaacc
            ccbcbaaacc
            acbcbbccacaccaccac
            ccbbcacaabcccabbbabbabbcababccaaccbc
            acaacaccbcbbaccbbaaaabbabbbbabbb
            cbaccacbbacbbcab
            cbbacacaccbaacaaaccacbcbbacacaabcbbccbabacc
            ccbaabbcaaacbaaaabbacaacbaabaabcacaacbbccccbaacbbbcbccbbacaaabbbcbccbb
            abccbcccbbccabbccbabbccccbaccbcbcbabbcbcaaccabbcccbaaabaabaaccbcbcbcccbbbaaccbcbcbaccbccccbccccacbc
            bbbcabccaccaacccaaaacbaabaaccbca
            abacabaaabacbbabbbcabcbcabcbabcbccbaacbabbaaaaccccccccccacbbaaaaccabccbbcabcabcbbbaabaacabbacbbb
            cabbccbccbaaacacaacbabbcaabcbbbbbcbaacacacabbaccbbacaccbcaabbc
            aabba
            acccabacbcaaaaaacbabccccaacb
            caacacacccaaaabbbcaabccacbaaaaaaaaab
            bbaabbbcccbaabbacbaaaacbcaccbbcccaccbbcbbcbcbaaaaacabcbacabbcbbabc
            aacbcbbcbccbcaaccabaaacccabcbacbaa
            acccaccabcbcccaaabccbaabbacacaacaacc
            bcbcabccaacbaaaaacbcccbacbaabcaacaaabcababbabbacbcbababbcaabcabcbcab
            aacbbc
            aaabccabbbaacaccbbcbbccbaaaccbacbabca
            bbbccacbacaabccbbbbbbacbabcabacccaccccbaccbacbbaabcbccaabcaaacccbccbcacca
            acbcabbbabaaccaaabacbbaaacabbbccbaaaabbaacbcbbcbcabbcbbbbbcbacaaabaabbbbacbcbbbbbccccaa
            ccbacaaacbbacccabbcccaaba
            bcabbabcbaacbaacacaaccbccbcaacbbacabcbb
            ccabaabaaccabacbcc
            aabbabcccaaabaccaabcbabcccaacaacaccbbbaaacabcaabbcaacbabaaaabaa
            aabbbccbbaccbbacaacaccaabababccbcaaabcacaabcbcbccbbcbbaacbaaba
            abbbccccaabcbbacbcabbbbcbaccbcacbcbabbacbababccabab
            c
            baacbcbbbaaacccabaaabcccabcbbccaacabcaababcac
            bbcbcbbcabbaaaacbba
            aacbbaabbaaabacbcab
            ccabababaaabaaaacbcabcbaaacccaccabaaabcbcbcbbababbbaaccb
            b
            accaaabbaaaccb
            bacabbbbacacbcbaa
            cbbaccbccacbcccccbbbccabbcaacbaaccacbccbacacbccbaccbbacaacbabcabc
            abcaccacaccaaacabbbacbbaccaabaccbbabcbbcabccbccbbbcaaabcacacaacbacacbbca
            bcbbcccbcacaacbccaabacbacbabaaabccbbabbaaaaaccaaaabbcaccbcababacabbbacbbcabaccaaccccccbacbbcc
            cabaccbaababbabccabbaabbabacbcbacabbccaccbbaccacabbaacbbbbbcbaab
            bbccbccaacaaacacaaaacbbbcaaabbbbaabbaaaacaaaababcbcccaaacbaabccbaabb
            bcbcbccccccabbacaabbcaaccccaabbcbcbcbccabbbcbcbbabaccbbbbccbabacacccbcacbaccacbaaabccabacbcbcabccccb
            bbabbabaccbcbbbccccabbabab
            caabbbcaaabbaccaaaaabcabbcaacbcccabcabcabcccbcacbaaccbbbababccbaaacbcbbbabbcccaacacccaccccacca
            aacbabbbcaaaccaccbbaaaccacbabbbacababaccbacaacbbbabbaabbaacbcaccabcac
            aaaccbcacabacababbbbbabaaacabcacabbaabbccabbaabbcabbcacaaaacacba
            acacabbaacaacaaabbcbcaaccaababbbaabbcabcbacbaabcccbccccbaccbbccbcbcbccbac
            cabacccbbabcbcbcacbacbcbacabaaccabaabbcabbcabbcbbbcaacaabbbccbbaaabbbbcc",
            Expected = @"
                       1
                       1
                       2
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       2
                       1
                       1
                       1
                       2
                       2
                       1
                       1
                       2
                       2
                       1
                       2
                       1
                       2
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       2
                       2
                       1
                       1
                       2
                       2
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       2
                       2
                       1
                       1
                       1
                       2
                       1
                       1
                       1
                       1
                       2
                       2
                       1
                       2
                       1
                       2
                       1
                       1
                       1
                       2
                       1
                       1
                       2
                       1
                       2
                       1
                       1
                       2
                       1
                       2
                       1
                       1
                       1
                       1
                       1
                       2
                       1
                       2
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       1
                       2
                       1
                       1
                       2
                       1"
        };
    }
}
